---
title: "Importing & Exporting Data with R"
author: "Aditya Dube"
date: "`r format(Sys.time(), '%A, %B %e, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading Packages

```{r message = FALSE, warning=FALSE}
library(data.table)
library(tidyverse)
library(knitr)
library(arrow)
library(bench)
library(ggbeeswarm)
library(haven)
```

## Import the possum.csv data directly from the URL
```{r }
possums <- read.csv("https://raw.githubusercontent.com/dilernia/STA418-518/main/Data/possum.csv")

# Printing first 6 columns and first 5 rows from the dataset
possums %>% dplyr::select(1:6) %>% 
  slice_head(n = 5) %>% kable()
```

## Importing using the import wizard

```{r }
possums_1 <- read_csv("possum.csv")
```

## Using read_csv
```{r }
possums <- read_csv("https://raw.githubusercontent.com/dilernia/STA418-518/main/Data/possum.csv")

# Printing first 6 columns and first 5 rows from the dataset
possums %>% dplyr::select(1:6) %>% 
  slice_head(n = 5) %>% kable()
```

## Using read_parquet

```{r }
possums <- read_parquet("possum.parquet")

# Printing first 8 columns and first 5 rows from the dataset
possums %>% dplyr::select(1:8) %>% 
  slice_head(n = 5) %>% kable()

```

## Using fread()
```{r }
possum_fread <- fread("https://raw.githubusercontent.com/dilernia/STA418-518/main/Data/possum.csv")

# Printing first 6 columns and first 5 rows from the dataset
possum_fread %>% dplyr::select(1:6) %>% 
  slice_head(n = 5) %>% kable()
```

## Comparing read speeds

```{r }
# Generating 'big data'
set.seed(1994)
x <- runif(5e4)
y <- runif(5e4)
x[sample(5e4, 5e3)] <- NA
y[sample(5e4, 5e3)] <- NA
bigData <- as.data.frame(x = x, y = y)
# Saving as CSV file w/ data.table
fwrite(bigData, "bigData.csv")
# Saving as parquet file
write_parquet(bigData, "bigData.parquet")
# Saving as RDS file
write_rds(bigData, "bigData.rds")
```

```{r}
# Comparing run times
readBmResult <- mark(read.csv("bigData.csv"), read_csv("bigData.csv",
                                                       show_col_types = FALSE),
                     fread("bigData.csv"), read_rds("bigData.rds"),
                     read_parquet("bigData.parquet", as_tibble = TRUE),
                     check = FALSE, min_iterations = 5)
ggObj <- plot(readBmResult)
importTimes <- ggObj$data %>% mutate(expression =
                                       paste0(map_chr(str_split(expression, pattern = "[(]"), 1), "()"))
# Printing table
importTimes %>% arrange(desc(median)) %>%
  select(expression:mem_alloc) %>% distinct() %>% knitr::kable()
```
```{r }
# Creating violin plots
importTimes %>% ggplot(aes(x = time, y = fct_reorder(expression, time))) +
  geom_violin(fill = "dodgerblue") +
  geom_jitter(
    height = 0.2,
    pch = 21,
    fill = "black",
    color = "white"
  ) +
  labs(title = "Comparison of read times", y = "", x = "Run time") +
  theme_bw()
```

## Reproduce the table and violin plots for write function

```{r }
# Comparing run times
writeBmResult <- mark(write.csv(bigData, "bigData.csv"), write_csv(bigData, "bigData.csv"),fwrite(bigData, "bigData.csv"), write_rds(bigData, "bigData.rds"), write_parquet(bigData, "bigData.parquet"),check = FALSE, min_iterations = 5)

ggObj <- plot(writeBmResult)

exportTimes <- ggObj$data %>% mutate(expression =
                                       paste0(map_chr(str_split(expression, pattern = "[(]"), 1), "()"))
# Printing table
exportTimes %>% arrange(desc(median)) %>%
  select(expression:mem_alloc) %>% distinct() %>% knitr::kable()

```
```{r }
# Creating violin plots
exportTimes %>% ggplot(aes(x = time, y = fct_reorder(expression, time))) +
  geom_violin(fill = "dodgerblue") +
  geom_jitter(
    height = 0.2,
    pch = 21,
    fill = "black",
    color = "white"
  ) +
  labs(title = "Comparison of write times", y = "", x = "Run time") +
  theme_bw()
```


